CREATE TABLE reports (
    id SERIAL PRIMARY KEY,
    month_of VARCHAR(100) NOT NULL,
    worker_name VARCHAR(100) NOT NULL,
    area_of_assignment VARCHAR(100) NOT NULL,
    name_of_church VARCHAR(100) NOT NULL,
    worship_service JSONB NOT NULL,
    sunday_school JSONB NOT NULL,
    prayer_meetings JSONB,
    bible_studies JSONB,
    mens_fellowships JSONB,
    womens_fellowships JSONB,
    youth_fellowships JSONB,
    child_fellowships JSONB,
    outreach JSONB,
    training_or_seminars JSONB,
    leadership_conferences JSONB,
    leadership_training JSONB,
    others JSONB,
    family_days JSONB,
    tithes_and_offerings JSONB,
    average_attendance DOUBLE PRECISION NOT NULL,
    worship_service_avg DOUBLE PRECISION,
    sunday_school_avg DOUBLE PRECISION,
    prayer_meetings_avg DOUBLE PRECISION,
    bible_studies_avg DOUBLE PRECISION,
    mens_fellowships_avg DOUBLE PRECISION,
    womens_fellowships_avg DOUBLE PRECISION,
    youth_fellowships_avg DOUBLE PRECISION,
    child_fellowships_avg DOUBLE PRECISION,
    outreach_avg DOUBLE PRECISION,
    training_or_seminars_avg DOUBLE PRECISION,
    leadership_conferences_avg DOUBLE PRECISION,
    leadership_training_avg DOUBLE PRECISION,
    others_avg DOUBLE PRECISION,
    family_days_avg DOUBLE PRECISION,
    tithes_and_offerings_avg DOUBLE PRECISION,
    home_visited JSONB,
    bible_study_or_group_led JSONB,
    sermon_or_message_preached JSONB,
    person_newly_contacted JSONB,
    person_followed_up JSONB,
    person_led_to_christ JSONB,
    names JSONB,
    home_visited_avg DOUBLE PRECISION,
    bible_study_or_group_led_avg DOUBLE PRECISION,
    sermon_or_message_preached_avg DOUBLE PRECISION,
    person_newly_contacted_avg DOUBLE PRECISION,
    person_followed_up_avg DOUBLE PRECISION,
    person_led_to_christ_avg DOUBLE PRECISION,
    narrative_report TEXT,
    challenges_and_problem_encountered TEXT,
    prayer_request TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_month_worker UNIQUE (month_of, worker_name)
);